/*欢迎使用MHY牌计算器V2！*/ 
#include<iostream> 
#include<string>
using namespace std;
int main()
{
	float i,n,a,b,g;
	string x;
	cout<<"欢迎使用MHY牌计算器V2！"<<endl;
	for(i=1;i>0;i++)
	{
		cout<<"加法模式按1；减法模式按2；乘法模式按3；除法模式按4；平方模式按5"<<endl;
		cin>>n;
		if(n==1)
		{
			for(g=1;g==1;g+=0)
			{
			  cout<<"加法模式,退出请输入s,使用请输入任意字符。";
			  cin>>x;
			  if(x=="s")
			  {
			  	     cout<<"已退出"<<endl;
					 break; 
			  }
			  cout<<"请输入第一个数字"<<endl;
			  cin>>a;
			  cout<<"请输入第二个数字"<<endl;
			  cin>>b;
			  cout<<a<<"+"<<b<<"="<<a+b<<endl;
		    }
		}
		if(n==2)
		{
			for(g=1;g==1;g+=0)
			{
			  cout<<"减法模式,退出请输入s,使用请输入任意字符。";
			  cin>>x;
			  if(x=="s")
			  {
			  	   cout<<"已退出"<<endl;
				   break;  
			  }
			  cout<<"请输入第一个数字"<<endl;
			  cin>>a;
			  cout<<"请输入第二个数字"<<endl;
			  cin>>b;
			  cout<<a<<"-"<<b<<"="<<a-b<<endl;
		    }
		}
		if(n==3)
		{
			for(g=1;g==1;g+=0)
			{
			  cout<<"乘法模式,退出请输入s,使用请输入任意字符。";
			  cin>>x;
			  if(x=="s")
			  {
			  	  cout<<"已退出"<<endl;
				   break;
			  }
			  cout<<"请输入第一个数字"<<endl;
			  cin>>a;
			  cout<<"请输入第二个数字"<<endl;
			  cin>>b;
			  cout<<a<<"*"<<b<<"="<<a*b<<endl;
		    }
		}
		if(n==4)
		{
			for(g=1;g==1;g+=0)
			{
			  cout<<"除法模式,退出请输入s,使用请输入任意字符。";
			  cin>>x;
			  if(x=="s")
			  {
			  	 cout<<"已退出"<<endl;
				   break; 
			  }
			  cout<<"请输入第一个数字"<<endl;
			  cin>>a;
			  cout<<"请输入第二个数字"<<endl;
			  cin>>a;
			  cout<<a<<"/"<<b<<"="<<a/b<<endl;
		    }
		}
		if(n==5)
		{
			for(g=1;g==1;g+=0)
			{
			  cout<<"平方模式,退出请输入s,使用请输入任意字符。";
			  cin>>x;
			  if(x=="s")
			  {
			  	     cout<<"已退出"<<endl;
					 break; 
			  }
			  cout<<"请输入数字"<<endl;
			  cin>>a;
			  cout<<a<<"*"<<a<<"="<<a*a<<endl;
		    }
		}
	}
	return 0;
}
